sudo: required
language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    env: COMPILER=g++-4.8
  - os: linux
    compiler: gcc
    env: COMPILER=g++-4.9
  - os: linux
    compiler: gcc
    env: COMPILER=g++-5
  - os: osx
    compiler: clang
    env: COMPILER=clang++

install:
  - ./.travis/install.sh

script:
  - mkdir build
  - cd build
  - export CXX=$COMPILER && cmake .. -DCMAKE_VERBOSE_MAKEFILE=ON && make CXX=$COMPILER

branches:
  only:
  - master
