{% set version = "0.8.dev" %}

package:
  name: caffe2
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  skip: True  # [win]
  script_env:
    - CONDA_CMAKE_ARGS

requirements:
  build:
    - future
    - glog
    - numpy
    - six
    - python
    - protobuf {{ protobuf }}
    - cmake
    - lmdb
    - snappy ==1.1.6
    - mkl-include
    - mkl
  run:
    - future
    - glog
    - numpy
    - six
    - python
    - protobuf
    - lmdb
    - snappy ==1.1.6
    - future
    - mkl-include
    - mkl

test:
  imports:
    - caffe2.python.core

about:
  home: https://caffe2.ai/
  license: BSD
  summary: Caffe2 is a lightweight, modular, and scalable deep learning framework.

extra:
  recipe-maintainers:
    - pjh5
